defaults: &defaults
  app_name: "whoru"
  domain: "http://whoru.herokuapp.com/"
  facebook_app_id: "561344750591272"
  facebook_secret: "9d14e83191a67c9d1ea1af431017b4ad"
  hipchat_token: 
  hipchat_room_name: 
  admin_emails: 
    - ""
  google_analytics_key: ""
  default_logo_url: "assets/logo-d6c87d9c7b7792c3585db6c7dfa2aaf6.png"
  page_desscription: "whoru is a way to understand people among each other"
  email_sender: ""

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
